# Generated by Django 4.0.5 on 2022-07-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_romano', models.CharField(help_text='Ingrese el nro de fase en numeros romanos', max_length=2)),
            ],
        ),
    ]
