# Generated by Django 4.0.5 on 2022-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fases',
            name='numero_romano',
            field=models.CharField(help_text='Ingrese el nro de fase en numeros romanos', max_length=3),
        ),
    ]
