# Generated by Django 4.0.5 on 2022-07-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelApp', '0002_alter_fases_numero_romano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la película', max_length=40)),
                ('sinopsis', models.TextField(help_text='Ingrese el resumen de la película')),
                ('anio', models.IntegerField(help_text='Ingrese el año de estreno  de la película')),
                ('duracion', models.IntegerField(help_text='Ingrese la duración en minutos de la película')),
                ('nro_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelApp.fases')),
            ],
        ),
    ]
