# Generated by Django 4.0.5 on 2022-07-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelApp', '0003_peliculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del personaje', max_length=30)),
                ('superpoder', models.CharField(help_text='Ingrese el superpoder del personaje', max_length=30)),
                ('actor_apellido', models.CharField(help_text='Ingrese el apellido del actor', max_length=30)),
                ('actor_nombre', models.CharField(help_text='Ingrese el nombre del actor', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personajes_Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelApp.peliculas')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarvelApp.personajes')),
            ],
        ),
    ]
